In [4]:
import torch

In [5]:
import numpy as np

In [6]:
print(torch.__version__)

2.9.1+cpu


In [7]:
# 1D Tensor
t1 = torch.tensor([1, 2, 3])

# 2D Tensor (Matrix)
t2 = torch.tensor([[1, 2], [3, 4]])

# 3D Tensor
t3 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
# printing shapes of the tensors
print(t1.shape, t2.shape, t3.shape)

torch.Size([3]) torch.Size([2, 2]) torch.Size([2, 2, 2])


In [8]:
# 1D Array
n1 = np.array([1, 2, 3])

# 2D Array
n2 = np.array([[1, 2], [3, 4]])

# 3D Array
n3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
# printing shapes of the numpy
print(n1.shape , n2.shape , n3.shape)

(3,) (2, 2) (2, 2, 2)


In [9]:
# creating two tensors 
a = torch.tensor([10, 20, 30])
b = torch.tensor([1, 2, 3])
# performing + , - , * , / operations 
print(a + b)
print(a - b)
print(a * b)
print(a / b)


tensor([11, 22, 33])
tensor([ 9, 18, 27])
tensor([10, 40, 90])
tensor([10., 10., 10.])


In [10]:
#creating two array 
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
# # performing + , - , * , / operations 
print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [11]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
# calculating dot product of 2 tensors
print(torch.dot(x, y))


tensor(32)


In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# calculating dot product of 2 arrays
print(np.dot(x, y))


32


In [13]:
# creating two 2x2 matrices 
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
# performing matrix multiplication 
print(torch.matmul(A, B))
# performing matrix multiplication by operator '@'
print("matrix multiplication by using operator '@' ")
print(A @ B)


tensor([[19, 22],
        [43, 50]])
matrix multiplication by using operator '@' 
tensor([[19, 22],
        [43, 50]])


In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# performing matrix multiplication
print(np.matmul(A, B))
# performing matrix multiplication by operator '@'
print("matrix multiplication by using operator '@' ")
print(A @ B)


[[19 22]
 [43 50]]
matrix multiplication by using operator '@' 
[[19 22]
 [43 50]]


In [15]:
t = torch.tensor([[10, 20, 30 ,324 ,34 ,54],
                  [40, 50, 60 ,23 , 43 , 4343]])
# First row
print(t[0])     
# Second column
print(t[:, 1])   
# Specific element
print(t[0, 5])    

tensor([ 10,  20,  30, 324,  34,  54])
tensor([20, 50])
tensor(54)


In [16]:
t = torch.tensor([1, 5, 10, 15])

mask = t > 5
print(mask)
print(t[mask])


tensor([False, False,  True,  True])
tensor([10, 15])


In [17]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

sub = t[0:2, 1:3]
print(sub)


tensor([[2, 3],
        [5, 6]])


In [18]:
t = torch.arange(6)

print(t.view(2, 3))


tensor([[0, 1, 2],
        [3, 4, 5]])


In [19]:
print(t.reshape(3, 2))


tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [28]:
t = torch.tensor([1, 2, 3])


print(t.shape)
print(t.unsqueeze(0).shape)  # Row vector
print(t.unsqueeze(1).shape)  # Column vector


torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


In [29]:
t = torch.tensor([[1, 2, 3]])

print(t.shape)
print(t.squeeze().shape)


torch.Size([1, 3])
torch.Size([3])


In [30]:
n = np.array([1, 2, 3])
print(n.reshape(1, 3))


[[1 2 3]]


In [31]:
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

b = torch.tensor([10, 20, 30])

print(A + b)


tensor([[11, 22, 33],
        [14, 25, 36],
        [17, 28, 39]])


In [32]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([10, 20, 30])

print(A + b)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [33]:
x = torch.tensor([1, 2, 3])
y = x + 5

print(x)
print(y)


tensor([1, 2, 3])
tensor([6, 7, 8])


In [34]:
x = torch.tensor([1, 2, 3])
x.add_(5)

print(x)


tensor([6, 7, 8])
